### ISSUE TITLE
执行 python -m cnstats --tree 报错

### ISSUE THREAD

**Issue by myt2000** [songjian/cnstats#4]
python -m cnstats --help
usage: cn-stats [-h] [--tree] [--list-regcode] [--dbcode [DBCODE]] [--regcode [REGCODE]] [zbcode] [date]

获取中国国家统计局网站数据Python包

positional arguments:
  zbcode               指标代码
  date                 查询日期

options:
  -h, --help           show this help message and exit
  --tree               列出指标代码
  --list-regcode       列出地区代码, 默认列出分省地区代码，列出主要城市代码添加 --dbcode csnd 参数
  --dbcode [DBCODE]    数据库代码, 默认: hgyd(宏观月度), 可选: hgjd(宏观季度), hgnd(宏观年度), fsyd(分省月度), fsjd(分省季度), fsnd(分省年度), csyd(城市月度), csjd(城市季度), csnd(城市年度)
  --regcode [REGCODE]  地区代码, 例如: 110000 是北京市

执行 python -m cnstats --tree 报错
 python -m cnstats --tree
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "E:\code\stats_test\venv\Lib\site-packages\cnstats\__main__.py", line 16, in <module>
    get_tree(args.tree, args.dbcode)
  File "E:\code\stats_test\venv\Lib\site-packages\cnstats\zbcode.py", line 4, in get_tree
    for n in easyquery(m='getTree', dbcode=dbcode, wdcode='zb', id=id):
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: easyquery() got an unexpected keyword argument 'wdcode'

**Comment by songjian** [comment]
你好，myt2000，

非常感谢你提交的这个bug反馈。目前这个问题已经修复，请升级最新的 v0.1.0 版本。感谢你对项目的支持和贡献！

祝好，  
sj
